name: 'Validate Workflow Pinning'
description: 'Validates that GitHub Actions in workflows are pinned to commit SHAs'

inputs:
  changed-files:
    description: 'Space-separated list of workflow files to check'
    required: true
  allow-unpinned:
    description: 'Space-separated list of allowed reusable workflows to permit in uses: clauses. No errors raised for these matches.'
    required: false
    default: ''
  fail-on-error:
    description: 'Whether to fail the action if unpinned actions are found'
    required: false
    default: 'true'

outputs:
  result:
    description: 'Result of the validation (success or failure)'
    value: ${{ steps.validate.outputs.result }}
  errors-found:
    description: 'Whether any errors were found'
    value: ${{ steps.validate.outputs.errors-found }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install ruamel.yaml
      shell: bash
    - name: Validate workflow pinning
      id: validate
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ inputs.changed-files }}
        FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
        ALLOW_UNPINNED: ${{ inputs.allow-unpinned }}
      run: python3 ${{ github.action_path }}/validate.py
